import 'package:taza/taza.dart';

class GroceryController extends GetxController{
  final List<Map<String, dynamic>> options = <Map<String, dynamic>>[];
  final List<Map<String, dynamic>> addresses = <Map<String, dynamic>>[];
  final RxList<String> hints = ['milk', 'ice cream', 'chips', 'coke'].obs;
  final RxInt currentHintIndex = 0.obs;
  TextEditingController searchController = TextEditingController();

  RxList<GroceryCategoryModel> groceryList = [
    GroceryCategoryModel(
      id: 'grocery',
      name: 'Grocery',
      subCategories: [
        SubCategoryModel(
          id: 'milk',
          name: 'Milk & Dairy',
          foods: [
            FoodModel(
              id: 'm1',
              name: 'Full Cream Milk',
              imageUrl: 'https://i.ibb.co/whRS5nY7/b.jpg',
              price: 3.5,
              isVeg: true,
              rating: 4.5,
              reviewsCount: 120,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm2',
              name: 'Toned Milk',
              imageUrl: 'https://i.ibb.co/XfpHPXFP/cake.jpg',
              price: 3.0,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 90,
              deliveryTime: '10-15 min',
            ),
            FoodModel(
              id: 'm3',
              name: 'Skimmed Milk',
              imageUrl: 'https://i.ibb.co/HLmQQsjy/chinease.jpg',
              price: 2.8,
              isVeg: true,
              rating: 4.0,
              reviewsCount: 70,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm4',
              name: 'Chocolate Milk',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 4.0,
              isVeg: true,
              rating: 4.6,
              reviewsCount: 150,
              deliveryTime: '20-25 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'veges',
          name: 'Vegetables & Fruits',
          foods: [
            FoodModel(
              id: 'v1',
              name: 'Tomato',
              imageUrl: 'https://i.ibb.co/Psj33M1h/pasta.jpg',
              price: 1.2,
              isVeg: true,
              rating: 4.1,
              reviewsCount: 110,
              deliveryTime: '12-18 min',
            ),
            FoodModel(
              id: 'v2',
              name: 'Carrot',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 1.0,
              isVeg: true,
              rating: 4.3,
              reviewsCount: 95,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'v3',
              name: 'Broccoli',
              imageUrl: 'https://i.ibb.co/MkqsDTsx/salad.jpg',
              price: 1.8,
              isVeg: true,
              rating: 4.4,
              reviewsCount: 80,
              deliveryTime: '20-25 min',
            ),
            FoodModel(
              id: 'v4',
              name: 'Spinach',
              imageUrl: 'https://i.ibb.co/07xdLSS/salad1.webp',
              price: 1.5,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 100,
              deliveryTime: '10-15 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'milk',
          name: 'Milk & Dairy',
          foods: [
            FoodModel(
              id: 'm1',
              name: 'Full Cream Milk',
              imageUrl: 'https://i.ibb.co/whRS5nY7/b.jpg',
              price: 3.5,
              isVeg: true,
              rating: 4.5,
              reviewsCount: 120,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm2',
              name: 'Toned Milk',
              imageUrl: 'https://i.ibb.co/XfpHPXFP/cake.jpg',
              price: 3.0,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 90,
              deliveryTime: '10-15 min',
            ),
            FoodModel(
              id: 'm3',
              name: 'Skimmed Milk',
              imageUrl: 'https://i.ibb.co/HLmQQsjy/chinease.jpg',
              price: 2.8,
              isVeg: true,
              rating: 4.0,
              reviewsCount: 70,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm4',
              name: 'Chocolate Milk',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 4.0,
              isVeg: true,
              rating: 4.6,
              reviewsCount: 150,
              deliveryTime: '20-25 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'veges',
          name: 'Vegetables & Fruits',
          foods: [
            FoodModel(
              id: 'v1',
              name: 'Tomato',
              imageUrl: 'https://i.ibb.co/Psj33M1h/pasta.jpg',
              price: 1.2,
              isVeg: true,
              rating: 4.1,
              reviewsCount: 110,
              deliveryTime: '12-18 min',
            ),
            FoodModel(
              id: 'v2',
              name: 'Carrot',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 1.0,
              isVeg: true,
              rating: 4.3,
              reviewsCount: 95,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'v3',
              name: 'Broccoli',
              imageUrl: 'https://i.ibb.co/MkqsDTsx/salad.jpg',
              price: 1.8,
              isVeg: true,
              rating: 4.4,
              reviewsCount: 80,
              deliveryTime: '20-25 min',
            ),
            FoodModel(
              id: 'v4',
              name: 'Spinach',
              imageUrl: 'https://i.ibb.co/07xdLSS/salad1.webp',
              price: 1.5,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 100,
              deliveryTime: '10-15 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'milk',
          name: 'Milk & Dairy',
          foods: [
            FoodModel(
              id: 'm1',
              name: 'Full Cream Milk',
              imageUrl: 'https://i.ibb.co/whRS5nY7/b.jpg',
              price: 3.5,
              isVeg: true,
              rating: 4.5,
              reviewsCount: 120,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm2',
              name: 'Toned Milk',
              imageUrl: 'https://i.ibb.co/XfpHPXFP/cake.jpg',
              price: 3.0,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 90,
              deliveryTime: '10-15 min',
            ),
            FoodModel(
              id: 'm3',
              name: 'Skimmed Milk',
              imageUrl: 'https://i.ibb.co/HLmQQsjy/chinease.jpg',
              price: 2.8,
              isVeg: true,
              rating: 4.0,
              reviewsCount: 70,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm4',
              name: 'Chocolate Milk',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 4.0,
              isVeg: true,
              rating: 4.6,
              reviewsCount: 150,
              deliveryTime: '20-25 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'veges',
          name: 'Vegetables & Fruits',
          foods: [
            FoodModel(
              id: 'v1',
              name: 'Tomato',
              imageUrl: 'https://i.ibb.co/Psj33M1h/pasta.jpg',
              price: 1.2,
              isVeg: true,
              rating: 4.1,
              reviewsCount: 110,
              deliveryTime: '12-18 min',
            ),
            FoodModel(
              id: 'v2',
              name: 'Carrot',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 1.0,
              isVeg: true,
              rating: 4.3,
              reviewsCount: 95,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'v3',
              name: 'Broccoli',
              imageUrl: 'https://i.ibb.co/MkqsDTsx/salad.jpg',
              price: 1.8,
              isVeg: true,
              rating: 4.4,
              reviewsCount: 80,
              deliveryTime: '20-25 min',
            ),
            FoodModel(
              id: 'v4',
              name: 'Spinach',
              imageUrl: 'https://i.ibb.co/07xdLSS/salad1.webp',
              price: 1.5,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 100,
              deliveryTime: '10-15 min',
            ),
          ],
        ),
      ],
    ),
    GroceryCategoryModel(
      id: 'grocery',
      name: 'Kitchen and more',
      subCategories: [
        SubCategoryModel(
          id: 'milk',
          name: 'Milk & Dairy',
          foods: [
            FoodModel(
              id: 'm1',
              name: 'Full Cream Milk',
              imageUrl: 'https://i.ibb.co/whRS5nY7/b.jpg',
              price: 3.5,
              isVeg: true,
              rating: 4.5,
              reviewsCount: 120,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm2',
              name: 'Toned Milk',
              imageUrl: 'https://i.ibb.co/XfpHPXFP/cake.jpg',
              price: 3.0,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 90,
              deliveryTime: '10-15 min',
            ),
            FoodModel(
              id: 'm3',
              name: 'Skimmed Milk',
              imageUrl: 'https://i.ibb.co/HLmQQsjy/chinease.jpg',
              price: 2.8,
              isVeg: true,
              rating: 4.0,
              reviewsCount: 70,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm4',
              name: 'Chocolate Milk',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 4.0,
              isVeg: true,
              rating: 4.6,
              reviewsCount: 150,
              deliveryTime: '20-25 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'veges',
          name: 'Vegetables & Fruits',
          foods: [
            FoodModel(
              id: 'v1',
              name: 'Tomato',
              imageUrl: 'https://i.ibb.co/Psj33M1h/pasta.jpg',
              price: 1.2,
              isVeg: true,
              rating: 4.1,
              reviewsCount: 110,
              deliveryTime: '12-18 min',
            ),
            FoodModel(
              id: 'v2',
              name: 'Carrot',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 1.0,
              isVeg: true,
              rating: 4.3,
              reviewsCount: 95,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'v3',
              name: 'Broccoli',
              imageUrl: 'https://i.ibb.co/MkqsDTsx/salad.jpg',
              price: 1.8,
              isVeg: true,
              rating: 4.4,
              reviewsCount: 80,
              deliveryTime: '20-25 min',
            ),
            FoodModel(
              id: 'v4',
              name: 'Spinach',
              imageUrl: 'https://i.ibb.co/07xdLSS/salad1.webp',
              price: 1.5,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 100,
              deliveryTime: '10-15 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'milk',
          name: 'Milk & Dairy',
          foods: [
            FoodModel(
              id: 'm1',
              name: 'Full Cream Milk',
              imageUrl: 'https://i.ibb.co/whRS5nY7/b.jpg',
              price: 3.5,
              isVeg: true,
              rating: 4.5,
              reviewsCount: 120,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm2',
              name: 'Toned Milk',
              imageUrl: 'https://i.ibb.co/XfpHPXFP/cake.jpg',
              price: 3.0,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 90,
              deliveryTime: '10-15 min',
            ),
            FoodModel(
              id: 'm3',
              name: 'Skimmed Milk',
              imageUrl: 'https://i.ibb.co/HLmQQsjy/chinease.jpg',
              price: 2.8,
              isVeg: true,
              rating: 4.0,
              reviewsCount: 70,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm4',
              name: 'Chocolate Milk',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 4.0,
              isVeg: true,
              rating: 4.6,
              reviewsCount: 150,
              deliveryTime: '20-25 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'veges',
          name: 'Vegetables & Fruits',
          foods: [
            FoodModel(
              id: 'v1',
              name: 'Tomato',
              imageUrl: 'https://i.ibb.co/Psj33M1h/pasta.jpg',
              price: 1.2,
              isVeg: true,
              rating: 4.1,
              reviewsCount: 110,
              deliveryTime: '12-18 min',
            ),
            FoodModel(
              id: 'v2',
              name: 'Carrot',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 1.0,
              isVeg: true,
              rating: 4.3,
              reviewsCount: 95,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'v3',
              name: 'Broccoli',
              imageUrl: 'https://i.ibb.co/MkqsDTsx/salad.jpg',
              price: 1.8,
              isVeg: true,
              rating: 4.4,
              reviewsCount: 80,
              deliveryTime: '20-25 min',
            ),
            FoodModel(
              id: 'v4',
              name: 'Spinach',
              imageUrl: 'https://i.ibb.co/07xdLSS/salad1.webp',
              price: 1.5,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 100,
              deliveryTime: '10-15 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'milk',
          name: 'Milk & Dairy',
          foods: [
            FoodModel(
              id: 'm1',
              name: 'Full Cream Milk',
              imageUrl: 'https://i.ibb.co/whRS5nY7/b.jpg',
              price: 3.5,
              isVeg: true,
              rating: 4.5,
              reviewsCount: 120,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm2',
              name: 'Toned Milk',
              imageUrl: 'https://i.ibb.co/XfpHPXFP/cake.jpg',
              price: 3.0,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 90,
              deliveryTime: '10-15 min',
            ),
            FoodModel(
              id: 'm3',
              name: 'Skimmed Milk',
              imageUrl: 'https://i.ibb.co/HLmQQsjy/chinease.jpg',
              price: 2.8,
              isVeg: true,
              rating: 4.0,
              reviewsCount: 70,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'm4',
              name: 'Chocolate Milk',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 4.0,
              isVeg: true,
              rating: 4.6,
              reviewsCount: 150,
              deliveryTime: '20-25 min',
            ),
          ],
        ),
        SubCategoryModel(
          id: 'veges',
          name: 'Vegetables & Fruits',
          foods: [
            FoodModel(
              id: 'v1',
              name: 'Tomato',
              imageUrl: 'https://i.ibb.co/Psj33M1h/pasta.jpg',
              price: 1.2,
              isVeg: true,
              rating: 4.1,
              reviewsCount: 110,
              deliveryTime: '12-18 min',
            ),
            FoodModel(
              id: 'v2',
              name: 'Carrot',
              imageUrl: 'https://i.ibb.co/Wp59vWJz/fries.jpg',
              price: 1.0,
              isVeg: true,
              rating: 4.3,
              reviewsCount: 95,
              deliveryTime: '15-20 min',
            ),
            FoodModel(
              id: 'v3',
              name: 'Broccoli',
              imageUrl: 'https://i.ibb.co/MkqsDTsx/salad.jpg',
              price: 1.8,
              isVeg: true,
              rating: 4.4,
              reviewsCount: 80,
              deliveryTime: '20-25 min',
            ),
            FoodModel(
              id: 'v4',
              name: 'Spinach',
              imageUrl: 'https://i.ibb.co/07xdLSS/salad1.webp',
              price: 1.5,
              isVeg: true,
              rating: 4.2,
              reviewsCount: 100,
              deliveryTime: '10-15 min',
            ),
          ],
        ),
      ],
    )
  ].obs;
  @override
  void onInit() {
    super.onInit();
    Timer.periodic(Duration(seconds: 2), (timer) {
      currentHintIndex.value = (currentHintIndex.value + 1) % hints.length;
    });

    printWrapped("GroceryController initialized");
  }
  void onTabSelected() {
    debugPrint('CartController → Tab Init');
  }
}